version: '3.7'
services:
    arango:
        image: arangodb:latest
        environment:
          ARANGO_ROOT_PASSWORD: rootarango2020
        ports:
          - 8529:8529
        volumes:
          - arangodb_data_container:/var/lib/arangodb3
          - arangodb_apps_data_container:/var/lib/arangodb3-apps
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
networks:
    nginx_default:
        external: true
